### ISSUE TITLE
Error (Failed to load & parse the details.json file.)

### ISSUE THREAD

**Issue by h4s33b** [pencilblue/devblog-pencilblue#5]
Hey there,

Thanks for this plugin. I have cloned the plugin in plugins folder and then pushed the files to heroku but getting an error on Plugins -> Manage 

Failed to load & parse the details.json file.
An invalid details file was provided for plugin. Error: ENOENT, open '/app/plugins/devblog-pencilblue/details.json' at Error (native)

I don`t know the reason because i can use the same plugin locally(localhost+mongodb) but i cant use it on heroku and i didn`t changed anything. I am using Heroku with mongoLab.

Thanks

**Comment by brianhyder** [comment]
That is a bit strange.  I think @blakecallens is more familiar with Heroku than I am.  Maybe he has some thoughts.  The only thing I can think of is that there aren't read permissions for that directory but would seem silly.  

A few questions:
- Is the error consistent?
- Did the file actually get uploaded as part of the deployment package?  
-  Did you install the plugin locally while connected to the same DB that you heroku PB instance is connected to?
- Can you send us the startup output from the heroku instance?

**Comment by blakecallens** [comment]
Yeah, that looks like a file read permission error. Maybe run a chmod -R
777 on the devblog folder and recommit?

**Comment by brianhyder** [comment]
@h4s33b Were you able to further investigate the issue?

**Comment by h4s33b** [comment]
Sorry Was out for a while.
I will soon respond about the issue. its still not fixed. I am working on it
