### ISSUE TITLE
Need help with blog.js controller

### ISSUE THREAD

**Issue by alexandrmatsyuk92** [pencilblue/devblog-pencilblue#7]
var section = self.req.pencilblue_section || null;
var topic = self.req.pencilblue_topic || null;
var article = self.req.pencilblue_article || null;
var page = self.req.pencilblue_page || null;

Hello. I can't understand in wich case there will be pencilblue_section or etc. in self.req

**Comment by brianhyder** [comment]
I do not believe that it will ever populate.  I think it is just copy/paste code from a previous blog controller that did not get removed.  

What has happened in the past is that the section controller (section.js) inherits from the blog controller after looking up the section in the DB.  It would hand off execution to the blog controller and the blog controller would know to look for the section in the req variable.  

Here I do not believe it is the case.  To my knowledge, no controllers inherit from the blog controller in this plugin.  Is there a specific use case that you are trying to implement?

@blakecallens is there something I'm missing?
